version: "3"

volumes:
  dbbackups:
  postgis-data:
  session-redis:
  access-redis:
services:
  sessions-service:
    image: session-service
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - default
    depends_on:
      - session-redis
    volumes:
      - ./logs-sessions:/app/logs
      - ./configs:/app/configs
  main:
    image: patreon
    expose:
      - "80"
      - "8080"
      - "443"
    ports:
      - "443:443"
      #      - "80:80"
      - "8080:8080"
    networks:
      - default
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./patreon-secrt:/app/patreon-secrt
      - ./configs:/app/configs
    depends_on:
      - session-redis
      - access-redis
      - patreon-bd
      - sessions-service
    environment:
      WAIT_HOSTS: patreon-bd:5432
  session-redis:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - session-redis:/data
  access-redis:
    image: "redis:alpine"
    expose:
      - "6380"
    ports:
      - "6380:6380"
    volumes:
      - access-redis:/data
  patreon-bd:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=pyaterochka
      - POSTGRES_USER=patreon
      - POSTGRES_DB=restapi_dev
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: 'node_exporter'
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - "9100"
    ports:
      - "9100:9100"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - node_exporter
    ports:
      - "3000:3000"
    expose:
      - "3000"
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4:5.7
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "m@mail.ru"
#      PGADMIN_DEFAULT_PASSWORD: "pyaterochka"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#    networks:
#      - postgres
networks:
  default:
    driver: bridge
