version: "3"

volumes:
  dbbackups:
  postgis-data:
  session-redis:
  access-redis:
services:
  ngnix-proxy:
    image: nginx:latest
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - main
      - grafana
      - prometheus
    networks:
      - default
    volumes:
      - ./logs-ngnix:/var/log/nginx/
      - ./patreon-secrt/api.pyaterochka-team.site:/etc/letsencrypt/live/api.pyaterochka-team.site
      - ./configs/nginx-local.conf:/etc/nginx/conf.d/default.conf
  sessions-service:
    image: session-service
    expose:
      - "5001"
      - "9091"
    ports:
      - "5001:5001"
    networks:
      - default
    depends_on:
      - session-redis
    volumes:
      - ./logs-sessions:/app/logs
      - ./configs:/app/configs
  files-service:
    image: files-service
    expose:
      - "5002"
      - "9091"
    ports:
      - "5002:5002"
    networks:
      - default
    volumes:
      - ./logs-files:/app/logs
      - ./media:/app/media
      - ./configs:/app/configs
  main:
    container_name: server
    image: patreon
    expose:
      - "8080"
    networks:
      - default
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./patreon-secrt:/app/patreon-secrt
      - ./configs:/app/configs
    depends_on:
      - session-redis
      - access-redis
      - patreon-bd
      - sessions-service
      - files-service
    environment:
      WAIT_HOSTS: patreon-bd:5432
  session-redis:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - session-redis:/data
  access-redis:
    image: "redis:alpine"
    expose:
      - "6380"
    ports:
      - "6380:6380"
    volumes:
      - access-redis:/data
  patreon-bd:
    image: pg-14
    expose:
      - "5432"
    command: "postgres -c shared_preload_libraries='pg_stat_statements'"
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=pyaterochka
      - POSTGRES_USER=patreon
      - POSTGRES_DB=restapi_dev
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  prometheus:
    image: prom/prometheus
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://localhost/prometheus'
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: 'node_exporter'
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - "9100"
    ports:
      - "9100:9100"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - node_exporter
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:80/grafana/
    expose:
      - "3000"
  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter
    environment:
#      DATA_SOURCE_URI: "patreon-bd:5432"
      DATA_SOURCE_USER: "patreon"
      DATA_SOURCE_PASS: "pyaterochka"
      DATA_SOURCE_URI: patreon-bd:5432/restapi_dev?sslmode=disable
    #      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    #    volumes:
    #      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    depends_on:
      - patreon-bd
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4:5.7
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "m@mail.ru"
#      PGADMIN_DEFAULT_PASSWORD: "pyaterochka"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#    networks:
#      - postgres
networks:
  default:
    driver: bridge
