global:
  scrape_interval:     20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: main
    metrics_path: '/metrics'
    static_configs:
      - targets: ['main:8080', 'sessions-service:9091']

  - job_name: node
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: postgres
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]