name: patreon-ci

on:
  [push, pull_request]

jobs:
  lint:
    name: ci-lint project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
