log_level = "debug"
log_path = "./logs/"
bind_addr = ":8080"
media_dir = "./media"

bind_addr_https = ":443"
bind_addr_http = ":80"

#domen = "95.163.208.72"
domen = "api.pyaterochka-team.site"

[local]
database_url = "port=5432 user=flashie password=1111 dbname=restapi_dev sslmode=disable"
session-redis_url = "redis://localhost:6379"

[server]
database_url = "host=patreon-bd port=5432 user=patreon password=pyaterochka dbname=restapi_dev sslmode=disable"
session-redis_url = "redis://session-redis/0"
access-redis_url = "redis://access-redis/0"


[cors]
headers = [
    "Accept", "Content-Type",
    "Content-Length", "Accept-Encoding",
    "X-CSRF-Token", "csrf-token",
    "Authorization"
]
methods = ["GET", "HEAD", "POST", "PUT", "OPTIONS", "DELETE"]
urls = [
    "http://pyaterochka-team.site", "https://pyaterochka-team.site",
   "http://dev.pyaterochka-team.site", "https://dev.pyaterochka-team.site",
   "http://localhost:3001", "http://localhost:8080", "https://patreon-dev.herokuapp.com",
    "https://dev-volodya-patreon.netlify.app", "https://patreon.netlify.app",
    "http://patreon-dev.herokuapp.com", "http://front2.tp.volodyalarin.site",
    "http://pyaterochka-team.site"
]
