name: patreon-ci-deploy

on:
  push:
    branches:
    - main
    - server_beta_4.1/main
  pull_request:
    branches:
      - main
      - server_beta_4.1/main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker image
        run: sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/session-service:${GITHUB_SHA::8} -f ./docker/session-service.Dockerfile . &&
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/files-service:${GITHUB_SHA::8} -f ./docker/files-service.Dockerfile . &&
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/main:${GITHUB_SHA::8} -f ./docker/builder.Dockerfile .

      - name: Push the image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/session-service:${GITHUB_SHA::8} &&
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/files-service:${GITHUB_SHA::8} &&
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/main:${GITHUB_SHA::8}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pull project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker rm 2021_2_pyaterochka_main_1
            sudo docker rm 2021_2_pyaterochka_sessions-service_1
            sudo docker rm 2021_2_pyaterochka_files-service_1
            cd tp/2021_2_Pyaterochka/ && sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/session-service:${GITHUB_SHA::8} &&
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/files-service:${GITHUB_SHA::8} &&
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/main:${GITHUB_SHA::8}
      - name: run project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
          cd tp/2021_2_Pyaterochka/ && sudo make run-https-back


